---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}

properties <- read.csv("properties_2016.csv")
```

```{r}
# Create sets for each county
county1 <- subset(properties, properties$regionidcounty == 1286)
county2 <- subset(properties, properties$regionidcounty == 2061)
county3 <- subset(properties, properties$regionidcounty == 3101)
```
## Data Summary

##### County 1
```{r}
# Number of records 
NROW(county1$taxvaluedollarcnt)

# Descriptive statistics
summary(county1$taxvaluedollarcnt)

# Binned ranges 
table(cut(county1$taxvaluedollarcnt, breaks=c(100000, 200000, 300000, 450000, 750000, 1000000, 5000000), labels=c("< 100000", "200,000", "300,000", "450,000", "750000", "> 1,000,000")))
```
##### County 2
```{r}
# Number of records 
NROW(county2$taxvaluedollarcnt)

# Descriptive statistics
summary(county2$taxvaluedollarcnt)

# Binned ranges 
table(cut(county2$taxvaluedollarcnt, breaks=c(100000, 200000, 300000, 450000, 750000, 1000000, 5000000), labels=c("< 100000", "200,000", "300,000", "450,000", "750000", "> 1,000,000")))
```

##### County 3
```{r}
# Number of records 
NROW(county3$taxvaluedollarcnt)

# Descriptive statistics
summary(county3$taxvaluedollarcnt)

# Binned ranges 
table(cut(county3$taxvaluedollarcnt, breaks=c(100000, 200000, 300000, 450000, 750000, 1000000, 5000000), labels=c("< 100000", "200,000", "300,000", "450,000", "750000", "> 1,000,000")))

```

```{r}
#Subsetting a range of variables that have too much missing value
 
 ind <- sapply( colnames(propertiesdata), function(x) sum(is.na(propertiesdata[[x]])) < nrow(propertiesdata)/2)
 propertiesdata <- propertiesdata[colnames(propertiesdata)[ind]]
 
 #convert the regiond id county to factor 
 
 as.factor(propertiesdata[, regionidcounty])
 
 # Calculating the mean in difference between prices and county 
 summary(aov(taxvaluedollarcnt ~ regionidcounty, data = propertiesdata))
 
 # Plotting it for visualization
 ggplot(data = propertiesdata, mapping = aes(x=regionidcounty, y=taxvaluedollarcnt)) + 
   stat_summary(fun.data = mean_cl_boot, geom='errorbar') + 
   stat_summary(fun.y = mean, geom = 'point', size=4) + 
   labs(x='', y='height (in)', title = 'Mean Height + 95% CI')
   ```
  ## Data Preparation
   
   ```{r}
   #Checking for numeric data and converting the attributes to numeric for linear model 
   
   checkNumeric<-function(x){
   if(!is.na(mean(as.numeric(as.character(x)),na.rm = T)) & 
      !is.nan(mean(as.numeric(as.character(x)),na.rm = T))){
     return(TRUE)
   }else{
     return(FALSE)
   }
 }
 
 Num_Propertiesdata<-propertiesdata_new[,sapply(propertiesdata_new, checkNumeric)]
 
 Num_PropertiesdataTrim<-apply(Num_Propertiesdata,2,as.numeric)
 Num_PropertiesdataTrim<-na.omit(na.approx(Num_PropertiesdataTrim))
 Num_PropertiesdataTrim<-as.data.frame(Num_PropertiesdataTrim)
  ```
 
 
 
 ## Simple Linear Model
 
 ##Linear model on the Properties dataset
 ```{r}
 PLM_model<-lm(taxvaluedollarcnt~.,Num_PropertiesdataTrim[,-1])
 summary(OLS_model)
 
 #finding multicollinearity 
 
 cormatrix<-cor(Num_PropertiesdataTrim[,-c(1,which(colnames(Num_PropertiesdataTrim)=="taxvaluedollarcnt"))])
 head(melt(cormatrix))
 ```
 
```{r}
# County 1
fit <- lm(county1$taxvaluedollarcnt ~ county1$bedroomcnt + county1$bathroomcnt, data = county1)
summary(fit)

# County 2
fit <- lm(county2$taxvaluedollarcnt ~ county2$bedroomcnt + county2$bathroomcnt, data = county2)
summary(fit)

# County 3
fit <- lm(county3$taxvaluedollarcnt ~ county3$bedroomcnt + county3$bathroomcnt, data = county3)
summary(fit)

```

## Additional models
